/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tree/tree.gltf --transform 
Files: public/models/tree/tree.gltf [8.58KB] > C:\xampp\htdocs\landscaping-frontend\tree-transformed.glb [10.63MB] (-123808%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tree-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.island_trees_01_blockout_cleaned.geometry} material={materials.island_tree_01} />
      <mesh geometry={nodes.island_trees_01_blockout_cleaned_1.geometry} material={materials.island_tree_01_leaves} />
      <mesh geometry={nodes.island_trees_01_blockout_cleaned_2.geometry} material={materials.island_tree_01_branches} />
    </group>
  )
}

useGLTF.preload('/tree-transformed.glb')
